# Group and current version of the plugin
pluginGroup = com.mhkarami.riderdemystifiedlinks
pluginName = rider-demystified-links
pluginVersion = 1.0.1

# See https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html for description
pluginSinceBuild = 233
pluginUntilBuild =

# IntelliJ Platform Artifacts Repositories -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html
platformType = RD
platformVersion = 2024.3

# Opt-out flag for bundling Kotlin standard library.
kotlin.stdlib.default.dependency = false

org.gradle.jvmargs=-Xmx2g

systemProp.javax.net.ssl.trustStoreType=Windows-ROOT
systemProp.java.security.KeyStore=Windows-ROOT